name: Create Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-release:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Stamp version
        run: Set-Content -Path src/__version__.py -Value "__version__ = ""${{ github.ref_name }}"""

      - name: Build executable
        run: pyinstaller --onefile --windowed --name TrackTitan-Downloader --icon=src/assets/icon.ico --add-data "src/assets;src/assets" tracktitan_downloader.py

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/TrackTitan-Downloader.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 